version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...

      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region eu-central-1 --no-include-email)
      - echo LOGGED

    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
      - mvn package
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...

      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS  --password-stdin 378582414855.dkr.ecr.eu-central-1.amazonaws.com

      - docker build -t aws-test-pka .

      - docker tag aws-test-pka:latest 378582414855.dkr.ecr.eu-central-1.amazonaws.com/aws_ecr_test:latest

      - docker push 378582414855.dkr.ecr.eu-central-1.amazonaws.com/aws_ecr_test:latest

      - echo Build completed on `date`

      - aws eks update-kubeconfig --name viper-eks-cluster --region eu-central-1
      
      - kubectl config get-contexts
      
      - kubectl get svc


#  aws ecr get-login-password --region eu-central-1 | docker login --username AWS  --password-stdin 378582414855.dkr.ecr.eu-central-1.amazonaws.com
